version: 2

models:

  - name: dim_customers
    description: Customer dimension with SCD Type 2 history.

    columns:

      - name: customer_sk
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: email
        tests:
          - not_null

      - name: is_current
        tests:
          - accepted_values:
              values: [true, false]


  - name: dim_accounts
    description: Account dimension with SCD Type 2 history.

    columns:

      - name: account_sk
        tests:
          - unique
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: account_status
        tests:
          - accepted_values:
              values:
                - Active
                - Closed
                - Frozen

      - name: currency
        tests:
          - accepted_values:
              values:
                - USD
                - EUR
                - INR


  - name: fact_transactions
    description: Transaction fact table.

    columns:

      - name: transaction_sk
        tests:
          - unique
          - not_null

      - name: transaction_id
        tests:
          - unique
          - not_null

      - name: account_sk
        tests:
          - relationships:
              to: ref('dim_accounts')
              field: account_sk

      - name: amount
        tests:
          - not_null

      - name: transaction_status
        tests:
          - accepted_values:
              values:
                - COMPLETED
                - FAILED
                - PENDING

      - name: transaction_type
        tests:
          - accepted_values:
              values:
                - DEPOSIT
                - WITHDRAWAL
                - TRANSFER